[package]
name = "nix-language-server"
version = "0.1.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
codespan = "0.4.1"
env_logger = "0.6.2"
futures = "0.1.28"
jsonrpc-core = "13.0"
jsonrpc-derive = "13.0"
jsonrpc-core-client = "13.0"
log = "0.4.7"
lsp-types = "0.59.0"
nom = "5.0.0"
rexpect = "0.3.0"
serde = { version = "1.0.94", features = ["derive"] }
serde_json = "1.0.40"
structopt = "0.2.18"
tokio = "0.1.22"
tower = "0.1.1"

[workspace]
members = ["nix-parser"]
