[package]
name = "nix-errors"
version = "0.1.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
edition = "2018"

[dependencies]
codespan = "0.9"
codespan-lsp = "0.9"
codespan-reporting = "0.9"
lsp-types = "0.73"
smallvec = "1.2"
